### ISSUE TITLE
User creation is throwing error with latest palm release

### ISSUE THREAD

**Issue by jramnai** [overhangio/tutor-cairn#4]
To reproduce this issue, set `CAIRN_ENABLE_SSO=false` and create a new user using following command:

`tutor local do cairn-createuser --admin YOURUSERNAME YOURUSERNAME@YOUREMAIL.COM`

This command will throw the following error:
```
docker compose -f /home/jayram/.local/share/tutor/env/local/docker-compose.yml -f /home/jayram/.local/share/tutor/env/local/docker-compose.prod.yml --project-name tutor_local -f /home/jayram/.local/share/tutor/env/local/docker-compose.jobs.yml run --rm cairn-superset-job sh -e -c 'python ./superset/cairn/ctl.py createuser  --admin YOURUSERNAME YOURUSERNAME@YOUREMAIL.COM'
[+] Building 0.0s (0/0)                                                                                                                                                                                   
[+] Creating 3/0
 ✔ Container tutor_local-permissions-1       Created                                                                                                                                                 0.0s 
 ✔ Container tutor_local-redis-1             Running                                                                                                                                                 0.0s 
 ✔ Container tutor_local-cairn-postgresql-1  Running                                                                                                                                                 0.0s 
[+] Running 1/1
 ✔ Container tutor_local-permissions-1  Started                                                                                                                                                      0.9s 
[+] Building 0.0s (0/0)                                                                                                                                                                                   
Loaded your LOCAL configuration at [/app/superset_config.py]
logging was configured successfully
2023-07-03 14:16:13,561:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
We haven't found any Content Security Policy (CSP) defined in the configurations. Please make sure to configure CSP using the TALISMAN_ENABLED and TALISMAN_CONFIG keys or any other external software. Failing to configure CSP have serious security implications. Check https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP for more information. You can disable this warning using the CONTENT_SECURITY_POLICY_WARNING key.
/usr/local/lib/python3.8/site-packages/flask_appbuilder/models/sqla/interface.py:67: SAWarning: relationship 'SqlaTable.slices' will copy column tables.id to column slices.datasource_id, which conflicts with relationship(s): 'Slice.table' (copies tables.id to slices.datasource_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="table"' to the 'SqlaTable.slices' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for prop in class_mapper(obj).iterate_properties:
Creating Superset DB: clickhousedb://YOURUSERNAME:@cairn-clickhouse:8123/openedx
Creating database reference for YOURUSERNAME
Creating user 'YOURUSERNAME'...
2023-07-03 14:16:15,372:ERROR:flask_appbuilder.security.sqla.manager:Error adding new user to database. 'str' object has no attribute '_sa_instance_state'
Traceback (most recent call last):
  File "./superset/cairn/ctl.py", line 256, in <module>
    main()
  File "./superset/cairn/ctl.py", line 88, in main
    args.func(args)
  File "./superset/cairn/ctl.py", line 114, in bootstrap_user
    raise RuntimeError(
RuntimeError: Failed to create user 'YOURUSERNAME' email='YOURUSERNAME@YOUREMAIL.COM'
Error: Command failed with status 1: docker compose -f /home/jayram/.local/share/tutor/env/local/docker-compose.yml -f /home/jayram/.local/share/tutor/env/local/docker-compose.prod.yml --project-name tutor_local -f /home/jayram/.local/share/tutor/env/local/docker-compose.jobs.yml run --rm cairn-superset-job sh -e -c python ./superset/cairn/ctl.py createuser  --admin YOURUSERNAME YOURUSERNAME@YOUREMAIL.COM

```
This issue is introduced with this commit: 5bf17dda912b8a81c125482f02f0b531e2bb0a72

Specifically this line: https://github.com/overhangio/tutor-cairn/commit/5bf17dda912b8a81c125482f02f0b531e2bb0a72#diff-ae0d5d9804316d65f08dc3eee67da957ad140b79a3fa26643aa7f4a1cc654ba8R109

**Comment by Faraz32123** [comment]
[This](https://github.com/overhangio/tutor-cairn/issues/4#:~:text=using%20following%20command%3A-,tutor%20local%20do%20cairn%2Dcreateuser%20%2D%2Dadmin%20YOURUSERNAME%20YOURUSERNAME%40YOUREMAIL.COM,-This%20command%20will) command is used to convert role of already existed LMS user to Admin, like 
`tutor local do cairn-createuser --admin YOURLMSUSERNAME YOURLMSUSERNAME@YOURLMSEMAIL.COM` as stated [here](https://github.com/overhangio/tutor-cairn#:~:text=Users%20authenticate%20with,YOURUSERNAME%40YOUREMAIL.COM).

By setting `CAIRN_ENABLE_SSO=false`, single sign-on with LMS user is disabled, You have to create new user using [these](https://github.com/overhangio/tutor-cairn#:~:text=SSO%20will%20then%20disabled%2C%20and,Demo_Course%27%20YOURUSERNAME%20YOURUSERNAME%40YOUREMAIL.COM) commands. You haven't given password argument in [your](https://github.com/overhangio/tutor-cairn/issues/4#:~:text=tutor%20local%20do%20cairn%2Dcreateuser%20%2D%2Dadmin%20YOURUSERNAME%20YOURUSERNAME%40YOUREMAIL.COM) command.

What do you think @regisb ?

**Comment by jramnai** [comment]
@Faraz32123 tried user creation command with password, but getting same issue.

Command: `tutor local do cairn-createuser --password=yourpassword test8 test8@example.com`

O/p:
```
docker compose -f /home/jayram/palm/env/local/docker-compose.yml -f /home/jayram/palm/env/local/docker-compose.prod.yml --project-name tutor_local -f /home/jayram/palm/env/local/docker-compose.jobs.yml run --rm cairn-superset-job sh -e -c 'python ./superset/cairn/ctl.py createuser --password=yourpassword  test8 test8@example.com'
[+] Running 3/0
 ⠿ Container tutor_local-permissions-1       Created                                                                                                                                                  0.0s
 ⠿ Container tutor_local-redis-1             Running                                                                                                                                                  0.0s
 ⠿ Container tutor_local-cairn-postgresql-1  Running                                                                                                                                                  0.0s
[+] Running 1/1
 ⠿ Container tutor_local-permissions-1  Started                                                                                                                                                       0.3s
Loaded your LOCAL configuration at [/app/superset_config.py]
logging was configured successfully
2023-07-05 12:52:34,453:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
We haven't found any Content Security Policy (CSP) defined in the configurations. Please make sure to configure CSP using the TALISMAN_ENABLED and TALISMAN_CONFIG keys or any other external software. Failing to configure CSP have serious security implications. Check https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP for more information. You can disable this warning using the CONTENT_SECURITY_POLICY_WARNING key.
/usr/local/lib/python3.8/site-packages/flask_appbuilder/models/sqla/interface.py:67: SAWarning: relationship 'SqlaTable.slices' will copy column tables.id to column slices.datasource_id, which conflicts with relationship(s): 'Slice.table' (copies tables.id to slices.datasource_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="table"' to the 'SqlaTable.slices' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for prop in class_mapper(obj).iterate_properties:
Creating Superset DB: clickhousedb://test8:@cairn-clickhouse:8123/openedx
Creating database reference for test8
Creating user 'test8'...
2023-07-05 12:52:35,548:ERROR:flask_appbuilder.security.sqla.manager:Error adding new user to database. 'str' object has no attribute '_sa_instance_state'
Traceback (most recent call last):
  File "./superset/cairn/ctl.py", line 256, in <module>
    main()
  File "./superset/cairn/ctl.py", line 88, in main
    args.func(args)
  File "./superset/cairn/ctl.py", line 114, in bootstrap_user
    raise RuntimeError(
RuntimeError: Failed to create user 'test8' email='test8@example.com'
Error: Command failed with status 1: docker compose -f /home/jayram/palm/env/local/docker-compose.yml -f /home/jayram/palm/env/local/docker-compose.prod.yml --project-name tutor_local -f /home/jayram/palm/env/local/docker-compose.jobs.yml run --rm cairn-superset-job sh -e -c python ./superset/cairn/ctl.py createuser --password=yourpassword  test8 test8@example.com
```
